import abjad


metadata = abjad.OrderedDict(
    [
        (
            'bol_measure_numbers',
            [56, 66, 76, 86],
            ),
        ('duration', "3'00''"),
        ('final_measure_number', 87),
        ('first_measure_number', 56),
        ('segment_name', 'ZB'),
        ('segment_number', 9),
        ('start_clock_time', "2'31''"),
        ('stop_clock_time', "5'31''"),
        (
            'time_signatures',
            [
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                '4/4',
                ],
            ),
        ]
    )
